// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import OrderItemsTableController from "./order_items_table_controller"
application.register("order-items-table", OrderItemsTableController)
