# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Components::Button`.
# Please instead update this file by running `bin/tapioca dsl Components::Button`.


class Components::Button
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
