# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Components::Link`.
# Please instead update this file by running `bin/tapioca dsl Components::Link`.


class Components::Link
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
